# Generated by Django 3.0.8 on 2021-03-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matno', models.CharField(max_length=25)),
                ('fullyear', models.CharField(max_length=15)),
                ('certificateno', models.CharField(max_length=20)),
                ('certimageurl', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursecode', models.CharField(max_length=20)),
                ('coursename', models.CharField(max_length=60)),
                ('deptcode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptcode', models.CharField(max_length=20)),
                ('deptname', models.CharField(max_length=60)),
                ('facid', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facid', models.CharField(max_length=30)),
                ('facname', models.CharField(max_length=60)),
                ('univcode', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Otps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otpid', models.CharField(max_length=25)),
                ('userid', models.CharField(max_length=25)),
                ('otpvalue', models.CharField(max_length=10)),
                ('expirydate', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nucno', models.CharField(max_length=50)),
                ('matno', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=20)),
                ('othernames', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=7)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('univcode', models.CharField(max_length=30)),
                ('facid', models.CharField(max_length=30)),
                ('deptcode', models.CharField(max_length=30)),
                ('courseofstudy', models.CharField(max_length=20)),
                ('yearofgrade', models.CharField(max_length=4)),
                ('fullyear', models.CharField(max_length=15)),
                ('photourl', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univcode', models.CharField(max_length=30)),
                ('uniname', models.CharField(max_length=150)),
                ('abbr', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('logo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
