# Generated by Django 3.0.8 on 2021-03-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='id',
        ),
        migrations.RemoveField(
            model_name='otps',
            name='id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='id',
        ),
        migrations.RemoveField(
            model_name='universities',
            name='id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='certificates',
            name='matno',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otps',
            name='otpid',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='matno',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='nucno',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='universities',
            name='univcode',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='userid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
