# Generated by Django 3.0.8 on 2021-03-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210301_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities',
            name='nucstatus',
            field=models.CharField(default='pending', max_length=10),
            preserve_default=False,
        ),
    ]
