# Generated by Django 3.0.8 on 2021-03-01 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_universities_nucstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universities',
            old_name='univcode',
            new_name='univemail',
        ),
        migrations.RemoveField(
            model_name='universities',
            name='email',
        ),
    ]
