# Generated by Django 3.0.8 on 2021-03-03 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_universities_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='facid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Faculties'),
        ),
    ]
